[package]
name = "timmy"
version = "0.1.0"
authors = ["Matthew Hall <matthew@quickbeam.me.uk>"]

[dependencies]
rusqlite = { version = "0.7.3", features = ["chrono"] }
clap = "2.10.0"
chrono = "0.2"
log = "0.3.6"
